# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp Parse Document Topics File either from --output-doc-topics or from the parsed state file.
#'
#' Allows for parsing information from the document terms matrix without loading the full thing into memory.
#' Can accept as input either the doc topics file output from MALLET, or the gzipped doc topics generated by
#' this package's rcpp_parse_topic_state function.
#' From the document topic matrix file this function extracts the top documents for each topic.
#' In addition, this function can optionally extract the top topics for each document, and if given as input
#' a vector containing the lengths of each document, can extract the topic frequency for each topic.
#'
#' @param fpath A string specifying the path to either the --output-doc-topics file or a gzipped doc topics file generated by this package.
#' @param topn A Number specifying the number of documents to save for each topic.
#' @param ttfile **optional** A string specifying the path to an output gzipped file in which to save the top topics for each document.
#' @param q **optional** A real number (defaults to 0.70) specifying the percentile of top topics to save for each document.
#' @param doc_lens **optional** An integer vector containing the number of tokens in each document, if provided, the topic frequencies are calculated.
#' @return A list with these components:
#' \describe{
#'   \item{top_docs_inds}{Numeric Matrix (K X topn) each cell has the index of the document starting at 0}
#'   \item{top_docs_values}{Numeric Matrix (K X topn) each cell has the doc topic score for the document, corresponds wiht top_docs_inds}
#'   \item{topic_frequencies}{A numeric vector of length(K) where each value is the topic proprotion, empty if doc_lens not provided}
#' }
#' @export
rcpp_parse_doc_topics <- function(fpath, topn, ttfile = "", q = 0.70, doc_lens = as.numeric( c())) {
    .Call(`_malletparseDSI_rcpp_parse_doc_topics`, fpath, topn, ttfile, q, doc_lens)
}

#' Rcpp Parse Topic State File --output-state
#'
#' Parses the file generated by Mallet with the --output-state flag.
#' The file is generally millions of lines long and is gzipped. 
#' The first three lines are meta information about the model.
#' Refer to the package README to see more about the file. 
#' This function is set up so that you can specify which information you want to extract from the state file.
#' If you have modeled a corpus with many millions of files, you will not be able to store the document topics matrix into memory.
#' In that case, set the dtflag to 0. 
#' To still extract the document topic matrix, set the dtfile parameter to the file you want to save the gzipped document topics matrix.
#' Writing it to file is done document by document and will not have any memory issues regardless of size, though may take up a lot of space on the disk.
#' This file contains all the information needed to run ldavis, look at the vignette for creating the json for ldavis with the information form the ifle.
#'
#' @param fpath A string specifying path to the output-state file.
#' @param termflag An integer (default = 1) set to 1 if you want to extract the terms and their frequencies.
#' @param docflag An integer (default = 1) set to 1 if you want to extract the document names and their token counts.
#' @param ttflag An integer (default = 1) set to 1 if you want to extract the topic terms matrix.
#' @param dtflag An integer (default = 1) set to 1 if you want to extract the document topic matrix. 
#' @param dtfile A string (default = "") specifying path to the output file you want to write the document topics to, leave blank if you don't want to write the doc topics to a file.
#' @return A list with these components:
#' \describe{
#'   \item{terms}{Character vector of the terms}
#'   \item{term_freqs}{Numeric vector of occurances for each term}
#'   \item{docs}{Character vector of the document names}
#'   \item{doc_lens}{Numeric vector of the number of tokens for each document}
#'   \item{topic_terms}{A matrix of topic terms (KxV)}
#'   \item{doc_topics}{A matrix of document topics (DxK)}
#'   \item{doc_topics_fpath}{A string with the path to the doc topics gzipped file}
#' }
#' @export
rcpp_parse_topic_state <- function(fpath, termflag = 1L, docflag = 1L, ttflag = 1L, dtflag = 1L, dtfile = "") {
    .Call(`_malletparseDSI_rcpp_parse_topic_state`, fpath, termflag, docflag, ttflag, dtflag, dtfile)
}

#' Rcpp Parse Topic Word Weights File --topic-word-weights
#'
#' Parses the file generated by Mallet with the --topic-word-weights flag.
#' The format is a whitespace delimited file, where each line has: topic (starting at 0) term weight.
#' Refer to the README for this package for more information about the topic-word-weights file.
#' Note that the weight seems to be count + beta parameter.
#'
#' @param fpath A string specifying path to the word-topic-counts text file.
#' @return topicterms A matrix with topic terms, terms as colnames.
#' @export
rcpp_parse_topic_word_weights <- function(fpath) {
    .Call(`_malletparseDSI_rcpp_parse_topic_word_weights`, fpath)
}

#' Rcpp Parse Topic Counts File --word-topic-counts
#'
#' Parses the file generated by Mallet with the --word-topic-counts flag.
#' The format is a whitespace delimited file, where each line has: termnumber term topic:count topic:count ...
#' Refer to the README for this package for more information about the word-topic-counts file.
#' Needs to know the number of topics. Returns the topic terms matrix.
#'
#' @param fpath A string specifying path to the word-topic-counts text file.
#' @param ntopics An integer representing the number of topics.
#' @return topicterms A matrix with topic terms, terms as colnames.
#' @export
rcpp_parse_word_topic_counts <- function(fpath, ntopics) {
    .Call(`_malletparseDSI_rcpp_parse_word_topic_counts`, fpath, ntopics)
}

